/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_HelloCJni */

#ifndef _Included_com_example_HelloCJni
#define _Included_com_example_HelloCJni
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_example_HelloCJni
 * Method:    getArch
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_HelloCJni_getArch (JNIEnv *, jclass);
/*
 * Class:     com_example_HelloCJni
 * Method:    hello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_HelloCJni_hello (JNIEnv *, jclass, jstring);



/*
 * Class:     com_example_HelloCJni
 * Method:    calculate
 * Signature: (II)I
 */
JNIEXPORT jstring JNICALL Java_com_example_HelloCJni_calculate (JNIEnv *, jclass, jint, jint);


#ifdef __cplusplus
}
#endif
#endif
